### ISSUE TITLE
change computer algorithm to positions searched instead move depth

### ISSUE THREAD

**Issue by SUPERETDUPER** [SUPERETDUPER/chess#10]
The computer algorithm searches a certain number of turns into the game. Instead it should analyse a number of positions. This would make endgames better and have a more consistent time. We could also consider combining both (aka. ex. min 4 turns in and min x moves analysed)

**Comment by SUPERETDUPER** [comment]
I tried except it's not easy. I only know of a recursive algorithm which requires dfs which means we need to be limited by a depth not a number of moves

**Comment by staadecker** [comment]
Should be possible but not necessarily desirable. See [here](https://stackoverflow.com/questions/19171015/minimax-algorithm-queue-possible).
